### ISSUE TITLE
AttributeError: 'PixelBuf' object has no attribute '_transmit' when entering light sleep

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_FunHouse#11]
When resuming from light sleep, the code crashes with this error:
```
Traceback (most recent call last):
  File "code.py", line 44, in <module>
  File "/lib/adafruit_funhouse/__init__.py", line 123, in enter_light_sleep
AttributeError: 'PixelBuf' object has no attribute '_transmit'
```

I'm not sure what happened since I had previously tested this, but will fix it as soon as I can figure out what is going on.

**Comment by makermelissa** [comment]
Ok, this seems to only happen when I compiled CircuitPython on my machine. The issue does not exist in 6.2.0.

**Comment by makermelissa** [comment]
Also, this occurred at any time when trying to set the dotstar values.

**Comment by makermelissa** [comment]
Ok, I looked at the boot out and it appears I have compiled on the 7.0.0 branch, so this is likely a 7.0.0 CircuitPython bug.
